[package]
name = "ln-primitives"
version = "2.0.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { path = "../../../primitives/api", default-features = false }
sp-runtime = { path = "../../../primitives/runtime", default-features = false }
rstd = { package = "sp-std", path = "../../../primitives/std", default-features = false }
[features]
default = ["std"]
std = [
  "codec/std",
  "rstd/std",
  "serde",
  "sp-runtime/std"
]
